name: wordsjson
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.8.3
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/word.json
    - assets/wordMP.json
    - assets/wordQZ.json

platforms:
  android:
